#!/bin/sh
rm -fv I* J* MOL* NEW* ACT* NAT* MO* OPT* GRD SYM* AOBA* TGUESS DIP* FCMF* FOCK* HF2*  VPOUT DE* POL* FCM* NO* FRQ* fort* AO* GAMLAM VM* ZMAT.BAS *.server LABBASIS BLOCKDATA BLOCK_INDEX cb.data ca.data ZMAT.AUTO AUXMOI aces3.restart
